### ISSUE TITLE
Can't access database via main thread

### ISSUE THREAD

**Issue by bijaykumarpun** [BijayKumarPun/room-db#3]
```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{rs.module.room/rs.module.room.MainActivity}: java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by bijaykumarpun** [comment]
Turns out accessing Room database instance from Main thread is not allowed unless `.allowMainThreadQueries()` is set while creating the database.
```
 val db = Room.databaseBuilder(this,AppDatabase::class.java,"my-database")
            .allowMainThreadQueries()
            .build()
```
A better approach is to use Kotlin coroutines.
